In [1]:
# Worksheet 1 Introduction to linear algebra
# Python equivalent of MATLAB code

import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
from numpy.linalg import svd, pinv
from sympy import symbols, Matrix, eye, det, solve, factor, simplify

# Clear all (equivalent to MATLAB's clear all; close all;)
plt.close('all')

# Define symbolic variables
a, b, c, d, lambda_var = symbols('a b c d lambda')

# Create symbolic matrix M
M = Matrix([[a, b], [c, d]])
dM = det(M)
print("Determinant of M:")
print(dM)

# How to invert a 3x3 matrix
# Create a symbolic 3x3 matrix
N = Matrix(3, 3, symbols('N:3:3'))
det_N = det(N)
print("\nSymbolic 3x3 matrix N:")
print(N)
print("\nDeterminant of N:")
print(det_N)

# SVD of matrix A of size 2 x 3
A = np.array([[4, 11, 14], [8, 7, -2]])
print("\nMatrix A:")
print(A)

# Construct B = A^T * A
B = A.T @ A
print("\nMatrix B = A^T * A:")
print(B)

# Converting B to symbolic matrix for symbolic calculations
B_sym = Matrix(B)

# Create C = B - lambda*I
C = B_sym - lambda_var * eye(3)
dC = det(C)
print("\nDeterminant of C = B - lambda*I:")
print(dC)
print("\nSimplified determinant:")
simplified_dC = simplify(dC)
print(simplified_dC)

# Solve the characteristic equation
eqn = -lambda_var**3 + 450*lambda_var**2 - 32400*lambda_var
S_values = solve(eqn, lambda_var)
print("\nEigenvalues:")
print(S_values)

# Factor the characteristic polynomial
factored_eqn = factor(-lambda_var**3 + 450*lambda_var**2 - 32400*lambda_var, lambda_var)
print("\nFactored characteristic equation:")
print(factored_eqn)

# Perform SVD
U, S_vals, Vt = svd(A)
V = Vt.T
S = np.zeros((2, 3))
S[:2, :2] = np.diag(S_vals)

print("\nU matrix from SVD:")
print(U)
print("\nS matrix from SVD:")
print(S)
print("\nV matrix from SVD:")
print(V)

# Check that (B - lambda_i * I) * v_i = 0
alpha = 360
print("\nChecking 360 * V[:, 0]:")
print(360 * V[:, 0])
print("\nChecking B * V[:, 0]:")
print(B @ V[:, 0])
print("\nAre they approximately equal?")
print(np.allclose(360 * V[:, 0], B @ V[:, 0]))

# Pseudo inverse and linear system
b = np.array([[1], [2]]).reshape(-1, 1)
print("\nVector b:")
print(b)

rank_A = np.linalg.matrix_rank(A)
print("\nRank of A:", rank_A)

Ab = np.hstack((A, b))
rank_Ab = np.linalg.matrix_rank(Ab)
print("Rank of [A b]:", rank_Ab)

# Calculate pseudoinverse
A_pinv = pinv(A)
print("\nPseudoinverse of A:")
print(A_pinv)

xstar = A_pinv @ b
print("\nSolution xstar = pinv(A) * b:")
print(xstar)

# Alternative ways to compute pseudoinverse
pseudo_A1 = V @ pinv(S) @ U.T
print("\nPseudoinverse computed using V * pinv(S) * U^T:")
print(pseudo_A1)

xstar1 = pseudo_A1 @ b
print("\nAlternative solution xstar1:")
print(xstar1)

St = S[:2, :2]
inv_StSt = np.linalg.inv(St.T @ St)
temp_matrix = np.zeros((3, 2))
temp_matrix[:2, :] = inv_StSt @ St.T
pseudo_A2 = V @ temp_matrix @ U.T
print("\nAnother pseudoinverse computation:")
print(pseudo_A2)

xstar2 = pseudo_A2 @ b
print("\nAlternative solution xstar2:")
print(xstar2)

Determinant of M:
a*d - b*c

Symbolic 3x3 matrix N:
Matrix([[N00, N01, N02], [N10, N11, N12], [N20, N21, N22]])

Determinant of N:
N00*N11*N22 - N00*N12*N21 - N01*N10*N22 + N01*N12*N20 + N02*N10*N21 - N02*N11*N20

Matrix A:
[[ 4 11 14]
 [ 8  7 -2]]

Matrix B = A^T * A:
[[ 80 100  40]
 [100 170 140]
 [ 40 140 200]]

Determinant of C = B - lambda*I:
-lambda**3 + 450*lambda**2 - 32400*lambda

Simplified determinant:
lambda*(-lambda**2 + 450*lambda - 32400)

Eigenvalues:
[0, 90, 360]

Factored characteristic equation:
-lambda*(lambda - 360)*(lambda - 90)

U matrix from SVD:
[[-0.9486833  -0.31622777]
 [-0.31622777  0.9486833 ]]

S matrix from SVD:
[[18.97366596  0.          0.        ]
 [ 0.          9.48683298  0.        ]]

V matrix from SVD:
[[-0.33333333  0.66666667 -0.66666667]
 [-0.66666667  0.33333333  0.66666667]
 [-0.66666667 -0.66666667 -0.33333333]]

Checking 360 * V[:, 0]:
[-120. -240. -240.]

Checking B * V[:, 0]:
[-120. -240. -240.]

Are they approximately equal?
True

Vector